/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gmap;

import java.awt.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.*;
import javax.swing.event.MouseInputListener;
import javax.swing.plaf.FontUIResource;

import com.soap.ws.client.generated.*;
import org.jxmapviewer.JXMapViewer;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.VirtualEarthTileFactoryInfo;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCursor;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;
import org.jxmapviewer.viewer.TileFactory;
import org.jxmapviewer.viewer.TileFactoryInfo;
import org.jxmapviewer.viewer.WaypointPainter;
import waypoint.EventWaypoint;
import waypoint.MyWaypoint;
import waypoint.WaypointRender;

/**
 *
 * @author saliya
 */
public class map extends javax.swing.JFrame {

    private final Set<MyWaypoint> waypoints = new HashSet<>();
    private EventWaypoint event;

    JXMapViewer mapViewer;
    double lat = 43.6826276;
    double lon = 7.2008549;

    public map() {
        initComponents();
        initx();
    }

    private void initx() {
        final List<TileFactory> factories = new ArrayList<TileFactory>();
        TileFactoryInfo osmInfo = new OSMTileFactoryInfo();
        TileFactoryInfo veInfo = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.MAP);
        factories.add(new DefaultTileFactory(osmInfo));
        factories.add(new DefaultTileFactory(veInfo));
        mapViewer = new JXMapViewer();
        mapViewer.setLayout(new BorderLayout());
        TileFactory firstFactory = factories.get(0);
        mapViewer.setTileFactory(firstFactory);

        GeoPosition geoPosition = new GeoPosition(lat, lon);

        mapViewer.setZoom(8);
        mapViewer.setAddressLocation(geoPosition);
        MouseInputListener mia = new PanMouseInputListener(mapViewer);
        mapViewer.addMouseListener(mia);
        mapViewer.addMouseMotionListener(mia);
        mapViewer.addMouseWheelListener(new ZoomMouseWheelListenerCursor(mapViewer));
        jPanel1.setLayout(new GridLayout());
        jPanel1.setPreferredSize(new Dimension(200, 200));
        jPanel1.add(mapViewer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        Font f = new Font("courrier", Font.BOLD, 12);

        origineLabel = new JLabel();
        origineLabel.setText("Origine : ");
        origineLabel.setFont(f);

        destinationLabel = new JLabel();
        destinationLabel.setText("Destination : ");
        destinationLabel.setFont(f);

        origineField = new JTextField();
        Dimension d = new Dimension(10,10);
        origineField.setPreferredSize(d);
        destinationField = new JTextField();
        destinationField.setPreferredSize(d);

        makeSearch = new JButton();
        makeSearch.setBackground(Color.magenta);
        makeSearch.setForeground(Color.WHITE);
        Dimension d2 = new Dimension(50,10);
        makeSearch.setPreferredSize(d2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );



        makeSearch.setText("Tracer itinéraire");
        makeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(origineLabel)
                    .addComponent(origineField)
                        .addComponent(destinationLabel)
                    .addComponent(destinationField)
                        .addComponent(makeSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(origineLabel)
                        .addComponent(origineField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(destinationLabel)
                        .addComponent(destinationField)
                            .addComponent(makeSearch)
                        .addGap(0, 500, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verifyField(JTextField org, JTextField dest){
        if((org.getText().equals("") || dest.getText().equals("")) || (org.getText().equals("") &&
                dest.getText().equals(""))){
            return false;
        }
        return true;
    }

    private void makeSearchActionPerformed(java.awt.event.ActionEvent evt){
        if(verifyField(origineField, destinationField)){
            RoutingService routingService = new RoutingService();
            IRoutingService iRoutingService = routingService.getBasicHttpBindingIRoutingService();

            String stationDepart = iRoutingService.getItineraire(origineField.getText(), destinationField.getText()).getStationDepart().getValue();
            String stationArrive = iRoutingService.getItineraire(origineField.getText(), destinationField.getText()).getStationArrivee().getValue();
            OpenRouteService DepartStationDepart = iRoutingService.getItineraire(origineField.getText(), destinationField.getText()).getDepartStationDepart().getValue();

            List<ArrayOfdouble> ad = DepartStationDepart.getFeatures().getValue().getFeature()
                    .get(0).getGeometry().getValue().getCoordinates().getValue().getArrayOfdouble();

            clearWaypoint();
            event = getEvent();
            addWaypoint(new MyWaypoint("w1", event, new GeoPosition(43.6267492, 6.9939829)));
            System.out.println(stationDepart);
            System.out.println(stationArrive);
        }
        else {
            JOptionPane.showMessageDialog(map.this, "L'origine et la destination doivent être renseignées");
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lat = lat + 0.0001;
        lon = lon + 0.0001;
        clearWaypoint();
        addWaypoint(new MyWaypoint("w1", event, new GeoPosition(lat, lon)));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lat = 7.291367349449556;
        lon = 80.63704388156131;
        clearWaypoint();
        addWaypoint(new MyWaypoint("w1", event, new GeoPosition(lat, lon)));
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new map().setVisible(true);
            }
        });
    }

    private void addWaypoint(MyWaypoint waypoint) {
        for (MyWaypoint d : waypoints) {
            mapViewer.remove(d.getButton());
        }
        waypoints.add(waypoint);
        initWaypoint();
    }

    private void initWaypoint() {
        WaypointPainter<MyWaypoint> wp = new WaypointRender();
        wp.setWaypoints(waypoints);
        mapViewer.setOverlayPainter(wp);
        for (MyWaypoint d : waypoints) {
            mapViewer.add(d.getButton());
        }
    }

    private void clearWaypoint() {
        for (MyWaypoint d : waypoints) {
            mapViewer.remove(d.getButton());
        }
        waypoints.clear();
        initWaypoint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;

    private JTextField origineField;
    private JTextField destinationField;

    private JLabel origineLabel;

    private JLabel destinationLabel;

    private JButton makeSearch;

    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private EventWaypoint getEvent() {
        return waypoint -> JOptionPane.showMessageDialog(map.this, waypoint.getName());
    }
}
